apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      tolerations:
      nodeSelector:
      containers:
        - name: frontend
          image: 457777705445.dkr.ecr.ap-southeast-2.amazonaws.com/johnw_repo:frontend_v1
          stdin: true
          tty: true
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_STOCK_ADDRESS
              value: "a45eab9ea987141498b49639c7fd69f9-804642524.ap-southeast-2.elb.amazonaws.com:82"
            - name: REACT_APP_USERS_ADDRESS
              value: "a28d8d65ade624aa5b17e24335dd3aef-1622519640.ap-southeast-2.elb.amazonaws.com:85"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "5"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "3"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: http
      port: 81
      targetPort: 3000
